#####################################
#          CityRP Paychecks         #
#             by: aDrew1            #
#####################################

Version: '1.1.0' # NO TOUCHY!
Version Check: true # Set to 'true' to perform version check on plugin load. Set to 'false' to disable.

#####################################
#              SETTINGS             #
#####################################

# USE /pc help TO VIEW COMMANDS!

# Permissions:
# cityrp.paychecks.admin - Allows usage of the help, reload, and send commands.

# Placeholders:
# %a% - Amount of money deposited.
# %p% - Player's name who is seeing the message. (For "Invalid Player", this variable will represent the target player!)

Prefix: '&c&lCityRP &8&l»'
Incorrect Usage: '&cError! &7Incorrect command usage. Use &e/paycheck help &7to see all commands.'
No Permission: '&cError! &7You do not have permission to do this!'
Invalid Player: '&cError! &e%p% &7was not found or is not online.'

Message:
  - ' '
  - '&c&lCityRP Paycheck'
  - '&eA Paycheck has been deposited to your account!'
  - '&7Deposited: &e$%a%'
  - ' '

Paycheck Frequency: 20 # in minutes

#####################################
#              PAYCHECKS            #
#####################################

Paychecks:
  100: # Add as many of these groups as you would like. You can name them anything.
    perm: 'cityrp.paycheck.100' # Set the permission to whatever you would like.
    amt: 100 # This amount must be a positive whole number (integer).
  200: # Add as many of these groups as you would like. You can name them anything.
    perm: 'cityrp.paycheck.200' # Set the permission to whatever you would like.
    amt: 200 # This amount must be a positive whole number (integer).