name: CityRP-Paycheck
version: '${project.version}'
main: io.github.adrew1dev.cityrppaycheck.CityRPPaycheck
api-version: 1.18
authors: [ aDrew1 ]
description: CityRP paycheck plugin. Receive paychecks after x amount of time.
website: mc.cityrp.us
softdepend:
  - Vault
commands:
  paycheck:
    description: /paycheck help
    usage: /paycheck
  pc:
    description: /pc help (Alias for /paycheck)
    usage: /pc
  paychecks:
    description: /paychecks help (Alias for /paycheck)
    usage: /paychecks
